// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPiYp2cqud75NYmIIwSJNa0pSt5G4LG4',
    appId: '1:743522612983:web:68e13caa3eb1c24197c5f2',
    messagingSenderId: '743522612983',
    projectId: 'crud-firebase-cea2f',
    authDomain: 'crud-firebase-cea2f.firebaseapp.com',
    storageBucket: 'crud-firebase-cea2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW6xGpSCpeVb9GZ3Tm3frk4qBFkGMR4R4',
    appId: '1:743522612983:android:b4e46e1abc254daf97c5f2',
    messagingSenderId: '743522612983',
    projectId: 'crud-firebase-cea2f',
    storageBucket: 'crud-firebase-cea2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8N6nE-6PqnTK11t9XARD_WHFaLZg_5c',
    appId: '1:743522612983:ios:c733424aaf21686397c5f2',
    messagingSenderId: '743522612983',
    projectId: 'crud-firebase-cea2f',
    storageBucket: 'crud-firebase-cea2f.appspot.com',
    iosClientId: '743522612983-7ojuqgdvpvcm9insp0r798i0a8ql61cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskCrudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8N6nE-6PqnTK11t9XARD_WHFaLZg_5c',
    appId: '1:743522612983:ios:c733424aaf21686397c5f2',
    messagingSenderId: '743522612983',
    projectId: 'crud-firebase-cea2f',
    storageBucket: 'crud-firebase-cea2f.appspot.com',
    iosClientId: '743522612983-7ojuqgdvpvcm9insp0r798i0a8ql61cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskCrudfirebase',
  );
}
